version: '3.8'
services:
  generator:
    depends_on:
      - database
    image: generator
    build: ./generator
    environment:
      MONGO_URL: ${MONGO_URL}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_IMAGE_BINARY: ${SERVER_IMAGE_BINARY}
    ports:
      - "4444:8080"
    networks:
      - db-network

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network


networks:
  db-network:

volumes:
  mongo-data: